//! Network mode: a real post-merge devnet rather than one node driven from the
//! host.
//!
//! Lab mode exists because it is instant. This exists because it is real. Three
//! execution clients, three *different* consensus clients, sixty-four
//! validators, discovery, gossip, attestations and finality — everything lab
//! mode skips. The cost is a minute to the first finalised epoch instead of a
//! chain that is simply there.
//!
//! The pieces come from elsewhere. Genesis and validator keys are generated by
//! ethPandaOps' image, the clients are the clients. What is written here is the
//! part no compose file can express: choosing a subnet that is free, deriving a
//! genesis whose contracts match lab mode byte for byte, and starting the
//! second wave of nodes only once the first has an ENR to give them.

use std::collections::BTreeMap;
use std::path::Path;
use std::process::Stdio;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result, bail};
use cupel_gateway::{Config as GatewayConfig, Gateway, Upstream};
use serde_json::Value;
use tokio::process::Command;

/// The genesis generator. There is no `latest` tag on this image — the tags are
/// versions — so pinning is not caution, it is the only option. It also means a
/// genesis generated today and one generated next year are the same genesis.
const GENERATOR: &str = "ethpandaops/ethereum-genesis-generator:6.2.1";

/// Carries `devp2p`, which is what makes the bootnode. geth's `bootnode` binary
/// was removed from go-ethereum and is no longer in any image.
const ALLTOOLS: &str = "ethereum/client-go:alltools-stable";

/// Used only to chown the generated tree back. Everything the generator writes
/// is owned by root, and a later `network init` cannot delete it otherwise.
const HELPER: &str = "alpine";

/// Enough validators for a committee per slot and few enough that generating
/// their keys takes seconds. Mainnet's default in this generator is 16384.
const VALIDATORS: usize = 64;

/// Twelve seconds, the same as mainnet, because it cannot be anything else.
///
/// This was six for two releases and never took effect. `SECONDS_PER_SLOT` is
/// not a value the genesis generator templates, so the key was absent from the
/// config it produced and every client used its preset default of twelve — a
/// chain running correctly at half the intended rate, with no error anywhere
/// and only one symptom: finality arriving twice as late as every comment here
/// promised.
///
/// Writing the key in by hand does not help either. Lighthouse validates the
/// config against the preset compiled into it and refuses to start:
///
/// ```text
/// YAML configuration incompatible with spec constants for mainnet
/// ```
///
/// Six-second slots need minimal-preset clients, which are different binaries
/// and a different chain shape. So the honest number is twelve, and four epochs
/// of thirty-two twelve-second slots is why a devnet takes about twenty-five
/// minutes to reach its first finalised epoch.
const SECONDS_PER_SLOT: u64 = 12;

/// What a client uses when the config declares no slot time. Lighthouse, Prysm
/// and Teku all compile the mainnet preset in, and all three fall back to this.
const MAINNET_SECONDS_PER_SLOT: u64 = 12;

/// How long after generation the beacon chain starts. Long enough for every
/// container to be up and listening before slot zero, short enough that nobody
/// waits.
const GENESIS_DELAY: u64 = 30;

/// Never. The generator's way of saying a fork does not happen on this chain.
const NEVER: &str = "18446744073709551615";

/// The mnemonic every validator key is derived from. It is the generator's own
/// default and is published in its repository; the keys it produces are
/// worthless anywhere but here.
const MNEMONIC: &str = "sleep moment list remain like wall lake industry canvas wonder ecology elite \
                        duck salad naive syrup frame brass utility club odor country obey pudding";

/// Where the beacon API of node one is published.
const CL1_URL: &str = "http://127.0.0.1:5052";

/// Node 1's QUIC port, as `network.yml` gives it to Lighthouse. Peers are
/// pointed at this rather than at the TCP port; see `static_peer`.
const CL_QUIC_PORT: u16 = 9001;

/// Prysm's wallet password, and the file compose tells Prysm to read it from.
/// `network.yml` must name the same file; a test below checks that it does.
const PRYSM_WALLET_PASSWORD: &str = "cupel";
const PRYSM_PASSWORD: &str = "prysm-password.txt";

/// The three nodes, their execution RPC, and the client each one runs.
pub(crate) const NODES: [Node; 3] = [
    Node {
        name: "node1",
        rpc: "http://127.0.0.1:8555",
        beacon: CL1_URL,
        consensus: "Lighthouse",
    },
    Node {
        name: "node2",
        rpc: "http://127.0.0.1:8556",
        beacon: "http://127.0.0.1:5152",
        consensus: "Prysm",
    },
    Node {
        name: "node3",
        rpc: "http://127.0.0.1:8557",
        beacon: "http://127.0.0.1:5252",
        consensus: "Teku",
    },
];

/// One execution client paired with one consensus client.
#[derive(Debug, Clone, Copy)]
pub(crate) struct Node {
    pub(crate) name: &'static str,
    pub(crate) rpc: &'static str,
    pub(crate) beacon: &'static str,
    pub(crate) consensus: &'static str,
}

// ---------------------------------------------------------------- generating

/// Generate a devnet: genesis, validator keys, a bootnode identity, and the
/// addresses everything will use.
pub(crate) async fn init(root: &Path) -> Result<()> {
    let dir = root.join("config/network");

    // The generator runs as root, so what it left behind cannot be removed by
    // the user who started it. Remove it from inside a container instead.
    if dir.exists() {
        docker(&[
            "run",
            "--rm",
            "-v",
            &format!("{}:/data", display(&dir)),
            HELPER,
            "sh",
            "-c",
            "rm -rf /data/* /data/.[!.]*",
        ])
        .await
        .ok();
        std::fs::remove_dir_all(&dir).ok();
    }
    std::fs::create_dir_all(&dir)?;

    let third = free_subnet(&docker_subnets().await?)
        .context("every candidate subnet in 172.x is already in use on this machine")?;
    let prefix = format!("172.{third}.0");
    let subnet = format!("{prefix}.0/24");
    println!("cupel: subnet {subnet}");

    let contracts = preloaded_contracts(root)?;
    println!(
        "cupel: carrying {} contracts from the lab genesis",
        contracts.matches("\"code\"").count()
    );

    // Genesis is stamped at generation time. Left at the generator's default of
    // zero the chain begins in 1970, and every client spends its first minutes
    // walking three hundred million empty slots before it will do anything.
    let now = SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs();

    println!("cupel: generating genesis and {VALIDATORS} validators");
    docker(&[
        "run",
        "--rm",
        "-e",
        "CHAIN_ID=31337",
        "-e",
        &format!("NUMBER_OF_VALIDATORS={VALIDATORS}"),
        "-e",
        &format!("GENESIS_TIMESTAMP={now}"),
        "-e",
        &format!("GENESIS_DELAY={GENESIS_DELAY}"),
        // Electra is the head of this chain, not Fulu, and that is a deliberate
        // step back from the tip.
        //
        // Fulu splits blob data into a hundred and twenty-eight column subnets.
        // Three nodes cannot cover that between them by stake, so each has to
        // custody everything, and each then subscribes to roughly two hundred
        // gossip topics. At that size the subscription exchange between clients
        // stopped working: Teku held a healthy connection to Lighthouse,
        // received gossip perfectly, and believed its peer was subscribed to
        // nothing — so all seventeen blocks it proposed, and every attestation
        // from its twenty-one validators, were published into the void. The
        // chain still finalised, on the other two nodes' 67%, which is how
        // close that failure came to going unnoticed.
        //
        // A lab should run the fork its clients agree on rather than the newest
        // one. PeerDAS interop on a three-node private network is a research
        // problem; teaching people about ERC-20 allowances is not.
        "-e",
        &format!("FULU_FORK_EPOCH={NEVER}"),
        // The premine is written out explicitly rather than derived from the
        // mnemonic, so network mode funds the same four accounts as lab mode.
        "-e",
        "EL_PREMINE_COUNT=0",
        "-e",
        &format!("EL_PREMINE_ADDRS={}", premine()),
        "-e",
        &format!("ADDITIONAL_PRELOADED_CONTRACTS={contracts}"),
        "-v",
        &format!("{}:/data", display(&dir)),
        GENERATOR,
        "all",
    ])
    .await
    .context("the genesis generator failed")?;

    for (index, (from, to)) in validator_ranges(VALIDATORS, NODES.len())
        .into_iter()
        .enumerate()
    {
        let node = NODES[index].name;
        // --insecure skips the scrypt work factor, turning key generation from
        // a minute into a second. It is correct here and nowhere else: these
        // keys come from a mnemonic printed in this file.
        docker(&[
            "run",
            "--rm",
            "--entrypoint",
            "eth2-val-tools",
            "-v",
            &format!("{}:/out", display(&dir)),
            GENERATOR,
            "keystores",
            "--insecure",
            "--prysm-pass",
            PRYSM_WALLET_PASSWORD,
            "--source-mnemonic",
            MNEMONIC,
            "--source-min",
            &from.to_string(),
            "--source-max",
            &to.to_string(),
            "--out-loc",
            &format!("/out/validators/{node}"),
        ])
        .await
        .with_context(|| format!("could not generate {node}'s validator keys"))?;
        println!("cupel: {node} holds validators {from}–{}", to - 1);
    }

    // A fixed identity for the bootnode, so the enode in the environment file
    // stays true for as long as this devnet exists.
    docker(&[
        "run",
        "--rm",
        "--entrypoint",
        "sh",
        "-v",
        &format!("{}:/data", display(&dir)),
        ALLTOOLS,
        "-c",
        &format!(
            "set -e; mkdir -p /data/bootnode; \
             devp2p key generate /data/bootnode/nodekey; \
             devp2p key to-enode --ip {prefix}.10 --tcp 30301 --udp 30301 \
               /data/bootnode/nodekey > /data/bootnode/enode"
        ),
    ])
    .await
    .context("could not create the bootnode identity")?;

    reclaim(root, &dir).await;

    testnet_dir(&dir)?;
    for node in NODES {
        // Prysm keeps its keys in a wallet rather than as loose keystores, and
        // reads the wallet's password from a file. The name has to match
        // compose exactly: getting it wrong costs a third of the stake, and
        // shows up as a chain that will not finalise — because a validator
        // client that cannot open its wallet is one that never attests, and it
        // says so in its own log rather than in the chain's.
        std::fs::write(
            dir.join("validators").join(node.name).join(PRYSM_PASSWORD),
            PRYSM_WALLET_PASSWORD,
        )
        .with_context(|| format!("could not write {}'s wallet password", node.name))?;
    }

    let enode = std::fs::read_to_string(dir.join("bootnode/enode"))
        .context("the bootnode wrote no enode")?
        .trim()
        .to_string();
    let key = std::fs::read_to_string(dir.join("bootnode/nodekey"))?
        .trim()
        .to_string();

    // Addresses are laid out by role rather than by allocation order, so that
    // .11 is always an execution client and .21 always a beacon node — which
    // makes a packet capture or a peer list readable without a key to hand.
    // Teku runs its validators in the beacon process, so there is no .33.
    let mut env = BTreeMap::new();
    env.insert("CUPEL_SUBNET".into(), subnet);
    env.insert("IP_BOOTNODE".into(), format!("{prefix}.10"));
    for index in 0..NODES.len() {
        let n = index + 1;
        env.insert(format!("IP_EL{n}"), format!("{prefix}.{}", 11 + index));
        env.insert(format!("IP_CL{n}"), format!("{prefix}.{}", 21 + index));
    }
    env.insert("IP_VC1".into(), format!("{prefix}.31"));
    env.insert("IP_VC2".into(), format!("{prefix}.32"));
    env.insert("EL_BOOTNODE".into(), enode);
    env.insert("EL_BOOTNODE_KEY".into(), key);
    // Both filled in by `up`, once node one's beacon node has an identity.
    env.insert("CL_BOOTNODE".into(), String::new());
    env.insert("CL_STATIC_PEER".into(), String::new());
    std::fs::write(dir.join("network.env"), render_env(&env))?;

    println!("cupel: devnet generated in config/network");
    Ok(())
}

/// Hand the generated tree back to whoever owns the checkout.
///
/// Every container above runs as root, so everything they wrote is root-owned
/// on the host: this process cannot read what it just generated, and the next
/// `network init` cannot delete it. The owner is taken from the checkout rather
/// than from `$UID`, which is a shell variable and is not in the environment.
#[cfg(unix)]
async fn reclaim(root: &Path, dir: &Path) {
    use std::os::unix::fs::MetadataExt;
    let Ok(meta) = std::fs::metadata(root) else {
        return;
    };
    let owner = format!("{}:{}", meta.uid(), meta.gid());
    docker(&[
        "run",
        "--rm",
        "-v",
        &format!("{}:/data", display(dir)),
        HELPER,
        "chown",
        "-R",
        &owner,
        "/data",
    ])
    .await
    .ok();
}

/// Windows has no such problem: the Docker Desktop file sharing layer presents
/// bind mounts as the calling user whatever the container wrote them as.
#[cfg(not(unix))]
async fn reclaim(_root: &Path, _dir: &Path) {}

/// Assemble the directory each consensus client is pointed at.
///
/// Same three files, and Lighthouse wants one of them under a different name.
fn testnet_dir(dir: &Path) -> Result<()> {
    let testnet = dir.join("testnet");
    std::fs::create_dir_all(&testnet)?;
    let meta = dir.join("metadata");
    for file in ["config.yaml", "genesis.ssz", "deposit_contract_block.txt"] {
        std::fs::copy(meta.join(file), testnet.join(file))
            .with_context(|| format!("the generator produced no {file}"))?;
    }
    std::fs::copy(
        meta.join("deposit_contract_block.txt"),
        testnet.join("deploy_block.txt"),
    )?;
    // No consensus bootnodes are known at generation time; node one's ENR is
    // passed on the command line once it exists.
    std::fs::write(testnet.join("boot_enr.yaml"), "[]\n")?;

    // Confirm the chain will run at the rate this file claims rather than
    // trusting that it does. Getting this wrong is silent: the clients start,
    // the chain is correct, and only the arithmetic in every comment is off.
    let config = std::fs::read_to_string(testnet.join("config.yaml"))?;
    let expected = SECONDS_PER_SLOT * 1000;
    match declared_slot_millis(&config) {
        Some(declared) if declared != expected => bail!(
            "the consensus config declares {declared}ms slots, not the {expected}ms \
             assumed here — every duration Cupel reports would be wrong"
        ),
        Some(_) => {}
        // Nothing declared: the clients fall back to their preset. That is the
        // state this chain was in for two releases, and it is benign only
        // because SECONDS_PER_SLOT equals the preset — which a test asserts.
        // Say it out loud, because reading the number from the file is the
        // stronger check and this run did not get to make it.
        None => println!(
            "cupel: the config declares no slot duration; the clients will use \
             the mainnet preset's {MAINNET_SECONDS_PER_SLOT}s"
        ),
    }
    Ok(())
}

/// The slot duration a consensus config declares, in milliseconds.
///
/// Two spellings, because the generator changed which one it writes. The check
/// above was added after the slot time turned out to be twelve seconds rather
/// than the six every comment assumed — and it read only `SECONDS_PER_SLOT`,
/// while the pinned generator writes `SLOT_DURATION_MS: 12000` and no
/// `SECONDS_PER_SLOT` at all. So it parsed nothing, took the preset fallback,
/// compared twelve with twelve, and passed. A guard written for exactly this
/// failure could not see the value it was guarding.
///
/// `None` means the config declares neither and the clients will use their
/// preset's default.
fn declared_slot_millis(config: &str) -> Option<u64> {
    let declared = |key: &str| {
        config
            .lines()
            .find_map(|line| line.trim_start().strip_prefix(key))
            .and_then(|value| value.split('#').next())
            .and_then(|value| value.trim().parse::<u64>().ok())
    };
    declared("SLOT_DURATION_MS:").or_else(|| declared("SECONDS_PER_SLOT:").map(|s| s * 1000))
}

// -------------------------------------------------------------- bringing up

/// Bring the devnet up, generating one first if there is no chain to resume.
pub(crate) async fn up(root: &Path, detach: bool, listen: std::net::IpAddr) -> Result<()> {
    let dir = root.join("config/network");

    // A chain that has already run must keep the genesis it started from. A
    // chain that has not must not keep a genesis stamped an hour ago, or every
    // client spends its first minutes walking empty slots to catch up. The
    // volumes decide which case this is.
    if !dir.join("network.env").is_file() || !has_chain_data().await? {
        init(root).await?;
    }

    println!("cupel: starting the bootnode and node 1");
    compose(root, &[], &["up", "-d", "--wait"]).await?;

    let path = dir.join("network.env");
    let mut env = parse_env(&std::fs::read_to_string(&path)?);
    if needs_identity(&env) {
        println!("cupel: waiting for node 1's beacon node");
        let host = env
            .get("IP_CL1")
            .cloned()
            .context("network.env has no IP_CL1")?;
        let (enr, peer_id) = wait_for_identity().await?;
        env.insert("CL_BOOTNODE".into(), enr);
        env.insert("CL_STATIC_PEER".into(), static_peer(&host, &peer_id));
        std::fs::write(&path, render_env(&env))?;
    }

    println!("cupel: starting nodes 2 and 3");
    compose(root, &["--profile", "peers"], &["up", "-d"]).await?;

    if detach {
        banner(None);
        return Ok(());
    }

    // The gateway written in phase C has, until now, had one upstream to choose
    // between. This is what it was for: three independent nodes, and a client
    // that keeps working when one of them stops. Stop a node and requests move
    // to the other two.
    //
    // Whether the chain also stops finalising depends on *which* node stopped,
    // and that is the part worth watching. See `stake_split` below: the three
    // nodes do not hold a third each, and the threshold counts validators.
    let gateway = Arc::new(Gateway::new(
        GatewayConfig::default(),
        NODES
            .iter()
            .map(|node| Upstream::new(node.name, node.rpc))
            .collect(),
    ));
    gateway.probe_once().await;

    // Bound here rather than inside the spawned task, so that a port already
    // held — by lab mode, or by a devnet gateway left running — is reported
    // instead of announced.
    let gateway_addr = std::net::SocketAddr::new(listen, crate::GATEWAY_PORT).to_string();
    let listener = crate::bind(&gateway_addr, "gateway").await?;
    let serving = tokio::spawn(cupel_gateway::serve_on(Arc::clone(&gateway), listener));
    let probing = tokio::spawn(Arc::clone(&gateway).probe_forever());

    // The same control room lab mode serves, on the same port, from the same
    // binary. It was reachable only from `cupel up` before, which made watching
    // a devnet in a browser require lab mode running as well — and lab mode
    // holds this gateway's port, so the two could never both start. Whichever
    // mode is running now serves the page, and the page works out which one it
    // is by asking the clients rather than by being told.
    //
    // With no producer: see `web::Control`.
    let control_addr = std::net::SocketAddr::new(listen, crate::CONTROL_ROOM_PORT).to_string();
    let control_listener = crate::web::bind(&control_addr).await?;
    let control = tokio::spawn(crate::web::serve_on(
        control_listener,
        crate::web::Control {
            mode: "network",
            producing: None,
        },
    ));

    let gateway_url = crate::url_for(listen, crate::GATEWAY_PORT);
    let control_url = crate::url_for(listen, crate::CONTROL_ROOM_PORT);
    banner(Some((&gateway_url, &control_url)));
    tokio::signal::ctrl_c().await.ok();
    println!();
    println!("cupel: the devnet keeps running — `cupel network down` stops it");

    serving.abort();
    probing.abort();
    control.abort();
    Ok(())
}

/// Whether node 1's identity still has to be fetched.
///
/// Only when it is missing. Node 1's identity survives its own restarts — same
/// key, same address, same ports — and all that moves is the ENR's sequence
/// number, which a peer bootstrapping from an older record simply refreshes.
///
/// Re-fetching it on every `up` looks harmless and is not: the new value goes
/// into the file compose interpolates, compose sees changed configuration for
/// nodes 2 and 3, and recreates them. Recreating a consensus client drops every
/// peer it had, so running `cupel network up` twice took the consensus layer
/// apart and left one client unable to find anyone at all.
fn needs_identity(env: &BTreeMap<String, String>) -> bool {
    ["CL_BOOTNODE", "CL_STATIC_PEER"]
        .iter()
        .any(|key| env.get(*key).is_none_or(String::is_empty))
}

/// Stop the devnet, optionally deleting every chain it produced.
pub(crate) async fn down(root: &Path, wipe: bool) -> Result<()> {
    let args: &[&str] = if wipe {
        println!("cupel: stopping the devnet and deleting its chains");
        &["down", "-v", "--remove-orphans"]
    } else {
        println!("cupel: stopping the devnet");
        &["down", "--remove-orphans"]
    };
    compose(root, &["--profile", "peers"], args).await
}

/// Ask each node where it thinks the chain is.
///
/// Three clients that agree are the point of running three clients, so the
/// numbers are shown side by side rather than summarised.
pub(crate) async fn status(_root: &Path) -> Result<()> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(3))
        .build()?;

    println!();
    println!("  node    consensus     block   slot   justified   finalized   peers");
    println!("  --------------------------------------------------------------------");
    let mut peerless = Vec::new();
    for node in NODES {
        let block = block_number(&client, node.rpc).await;
        let (slot, justified, finalized) = beacon_state(&client, node.beacon).await;
        let peers = peer_count(&client, node.beacon).await;
        if peers == "0" {
            peerless.push(node.consensus);
        }
        println!(
            "  {:<7} {:<12} {:>6} {:>6} {:>11} {:>11} {:>7}",
            node.name, node.consensus, block, slot, justified, finalized, peers
        );
    }
    println!();

    // Peers earn a column because a client with none is the failure this mode
    // actually produces, and it is invisible everywhere else: blocks still
    // propagate, every client still agrees, no slot is missed — and nothing
    // justifies, because a client in no gossip mesh publishes its attestations
    // into nothing.
    if !peerless.is_empty() {
        println!(
            "  {} has no peers — it will follow the chain and attest to nothing.",
            peerless.join(" and ")
        );
        println!();
    }
    Ok(())
}

/// How many peers a beacon node believes it is connected to.
///
/// Each client counts this differently and one of them is capable of reporting
/// none while it is demonstrably gossiping, so this is what the node says about
/// itself, not a measurement.
async fn peer_count(client: &reqwest::Client, beacon: &str) -> String {
    let Ok(response) = client
        .get(format!("{beacon}/eth/v1/node/peer_count"))
        .send()
        .await
    else {
        return "—".into();
    };
    match response.json::<Value>().await {
        Ok(value) => value
            .pointer("/data/connected")
            .and_then(Value::as_str)
            .map(str::to_string)
            .unwrap_or_else(|| "—".into()),
        Err(_) => "—".into(),
    }
}

async fn block_number(client: &reqwest::Client, rpc: &str) -> String {
    let body = serde_json::json!({
        "jsonrpc": "2.0", "id": 1, "method": "eth_blockNumber", "params": []
    });
    let Ok(response) = client.post(rpc).json(&body).send().await else {
        return "—".into();
    };
    let Ok(value): Result<Value, _> = response.json().await else {
        return "—".into();
    };
    value
        .pointer("/result")
        .and_then(Value::as_str)
        .and_then(|hex| u64::from_str_radix(hex.trim_start_matches("0x"), 16).ok())
        .map(|n| n.to_string())
        .unwrap_or_else(|| "—".into())
}

/// Head slot, and the epochs this node considers justified and finalised.
async fn beacon_state(client: &reqwest::Client, beacon: &str) -> (String, String, String) {
    let dash = || "—".to_string();
    let syncing = client
        .get(format!("{beacon}/eth/v1/node/syncing"))
        .send()
        .await;
    let slot = match syncing {
        Ok(response) => match response.json::<Value>().await {
            Ok(value) => value
                .pointer("/data/head_slot")
                .and_then(Value::as_str)
                .map(str::to_string)
                .unwrap_or_else(dash),
            Err(_) => dash(),
        },
        Err(_) => return (dash(), dash(), dash()),
    };

    let checkpoints = client
        .get(format!(
            "{beacon}/eth/v1/beacon/states/head/finality_checkpoints"
        ))
        .send()
        .await;
    let (justified, finalized) = match checkpoints {
        Ok(response) => match response.json::<Value>().await {
            Ok(value) => (
                value
                    .pointer("/data/current_justified/epoch")
                    .and_then(Value::as_str)
                    .map(str::to_string)
                    .unwrap_or_else(dash),
                value
                    .pointer("/data/finalized/epoch")
                    .and_then(Value::as_str)
                    .map(str::to_string)
                    .unwrap_or_else(dash),
            ),
            Err(_) => (dash(), dash()),
        },
        Err(_) => (dash(), dash()),
    };
    (slot, justified, finalized)
}

/// Poll node one's beacon API for the two things its peers need: an ENR to
/// discover it by, and a peer id to dial it at directly.
///
/// Nodes two and three cannot start before this. A consensus client finds peers
/// from an ENR, and node one's ENR does not exist until node one does — the
/// dependency compose cannot express, and most of the reason there is a control
/// plane here rather than a third compose file.
async fn wait_for_identity() -> Result<(String, String)> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(2))
        .build()?;
    for _ in 0..60 {
        if let Ok(response) = client
            .get(format!("{CL1_URL}/eth/v1/node/identity"))
            .send()
            .await
            && let Ok(value) = response.json::<Value>().await
            && let Some(enr) = value.pointer("/data/enr").and_then(Value::as_str)
            && let Some(peer_id) = value.pointer("/data/peer_id").and_then(Value::as_str)
        {
            return Ok((enr.to_string(), peer_id.to_string()));
        }
        tokio::time::sleep(Duration::from_secs(1)).await;
    }
    bail!("node 1's beacon node never reported an identity — check `docker logs cupel-cl1`")
}

/// Where a peer should dial node 1: over QUIC, not TCP.
///
/// This is built rather than read from the identity endpoint, which advertises
/// only the TCP address. Both work at the connection level and the difference
/// shows up a layer above: over TCP, Teku held a connection, received gossip
/// perfectly well, and could publish none of its own — it never appeared in
/// Lighthouse's gossip mesh, so it knew of no peer subscribed to the topics it
/// needed. Twenty-one validators attested into nothing, and the only symptom
/// was justification that would not advance. Over QUIC it joins the mesh.
///
/// Prysm reaches node 1 through discovery and is given no static peer at all,
/// for a related reason recorded in `network.yml`.
fn static_peer(host: &str, peer_id: &str) -> String {
    format!("/ip4/{host}/udp/{CL_QUIC_PORT}/quic-v1/p2p/{peer_id}")
}

// -------------------------------------------------------------------- pieces

/// Every contract in the lab genesis, in the form the generator expects.
///
/// The bytecode comes from the committed lab genesis rather than from Foundry,
/// so the two modes provably carry identical contracts at identical addresses
/// and generating a devnet needs no Solidity toolchain.
fn preloaded_contracts(root: &Path) -> Result<String> {
    let path = root.join("config/genesis/genesis.json");
    let raw = std::fs::read_to_string(&path)
        .with_context(|| format!("could not read {}", display(&path)))?;
    let genesis: Value = serde_json::from_str(&raw)?;
    let alloc = genesis
        .get("alloc")
        .and_then(Value::as_object)
        .context("the lab genesis has no alloc")?;

    let mut out = serde_json::Map::new();
    for (address, account) in alloc {
        if let Some(code) = account.get("code") {
            out.insert(
                address.clone(),
                serde_json::json!({ "balance": "0", "code": code }),
            );
        }
    }
    if out.is_empty() {
        bail!("the lab genesis carries no contracts — run `cupel genesis` first");
    }
    Ok(serde_json::to_string(&Value::Object(out))?)
}

/// The four development accounts, funded as generously as in lab mode.
fn premine() -> String {
    let mut out = serde_json::Map::new();
    for (address, _) in crate::DEV_ACCOUNTS {
        out.insert(
            address.to_string(),
            serde_json::json!({ "balance": "10000ETH" }),
        );
    }
    serde_json::to_string(&Value::Object(out)).unwrap_or_default()
}

/// Split validators as evenly as possible, remainder to the earliest nodes.
fn validator_ranges(total: usize, nodes: usize) -> Vec<(usize, usize)> {
    let mut ranges = Vec::with_capacity(nodes);
    let mut next = 0;
    for index in 0..nodes {
        let share = total / nodes + usize::from(index < total % nodes);
        ranges.push((next, next + share));
        next += share;
    }
    ranges
}

/// Choose the second octet of a free `172.x.0.0/24`.
///
/// A fixed subnet is the obvious thing to write and it fails the moment another
/// project on the machine has taken it, with a Docker error that names no
/// culprit. 17 through 23 are skipped because Docker hands them out itself, and
/// 29 because that is where WSL puts its own interface — taking it would cut
/// the host off from its network to run a devnet.
fn free_subnet(taken: &[String]) -> Option<u8> {
    let used: Vec<u8> = taken
        .iter()
        .filter_map(|subnet| {
            let mut parts = subnet.split('.');
            (parts.next()? == "172").then(|| parts.next()?.parse().ok())?
        })
        .collect();
    [24, 25, 26, 27, 28, 30, 31, 32]
        .into_iter()
        .find(|candidate| !used.contains(candidate))
}

/// Every subnet Docker has already allocated on this machine.
async fn docker_subnets() -> Result<Vec<String>> {
    let ids = docker(&["network", "ls", "-q"]).await?;
    let mut subnets = Vec::new();
    for id in ids.split_whitespace() {
        let out = docker(&[
            "network",
            "inspect",
            "-f",
            "{{range .IPAM.Config}}{{.Subnet}} {{end}}",
            id,
        ])
        .await
        .unwrap_or_default();
        subnets.extend(out.split_whitespace().map(str::to_string));
    }
    Ok(subnets)
}

/// Whether any node has a chain on disk already.
async fn has_chain_data() -> Result<bool> {
    let out = docker(&["volume", "ls", "-q", "--filter", "name=cupel-el"]).await?;
    Ok(!out.trim().is_empty())
}

fn parse_env(text: &str) -> BTreeMap<String, String> {
    text.lines()
        .filter_map(|line| line.split_once('='))
        .map(|(key, value)| (key.to_string(), value.to_string()))
        .collect()
}

fn render_env(vars: &BTreeMap<String, String>) -> String {
    let mut out = String::from("# Written by `cupel network init`. Read by compose.\n");
    for (key, value) in vars {
        out.push_str(key);
        out.push('=');
        out.push_str(value);
        out.push('\n');
    }
    out
}

async fn compose(root: &Path, before: &[&str], args: &[&str]) -> Result<()> {
    let file = root.join("compose/network.yml");
    let env = root.join("config/network/network.env");
    let status = Command::new("docker")
        .arg("compose")
        .arg("-f")
        .arg(&file)
        .arg("--env-file")
        .arg(&env)
        .args(before)
        .args(args)
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .await
        .context("could not run `docker compose` — is Docker running?")?;
    if !status.success() {
        bail!("docker compose {} failed", args.join(" "));
    }
    Ok(())
}

/// Run docker and hand back its output. Progress goes to the terminal; only
/// what the command printed is returned.
async fn docker(args: &[&str]) -> Result<String> {
    let output = Command::new("docker")
        .args(args)
        .stderr(Stdio::inherit())
        .output()
        .await
        .context("could not run `docker` — is Docker running?")?;
    if !output.status.success() {
        bail!("docker {} failed", args.first().copied().unwrap_or("?"));
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn display(path: &Path) -> String {
    path.display().to_string()
}

/// The container to stop when demonstrating the threshold.
///
/// Named rather than written into the banner, because which node it has to be
/// is arithmetic, not prose — `only_one_node_holds_enough_stake_to_stop_finality`
/// derives it from the split and fails if this constant stops matching.
const DEMO_STOP_CONTAINER: &str = "cupel-el1";

/// How many validators each node ends up driving.
///
/// Sixty-four across three nodes is 22 / 21 / 21, not a third each:
/// `validator_ranges` gives the remainder to the first node. Every sentence
/// about stopping a node depends on that, so nothing restates it by hand.
pub(crate) fn stake_split() -> Vec<usize> {
    validator_ranges(VALIDATORS, NODES.len())
        .iter()
        .map(|(first, end)| end - first)
        .collect()
}

/// Whether a given number of attesting validators can justify an epoch.
///
/// Strictly *more* than two thirds, kept in integers so the boundary case is
/// exact: with 64 validators, 42 is not enough and 43 is.
pub(crate) fn finalises(attesting: usize) -> bool {
    attesting * 3 > VALIDATORS * 2
}

/// The smallest number of validators that can justify an epoch.
pub(crate) fn votes_needed() -> usize {
    (0..=VALIDATORS)
        .find(|n| finalises(*n))
        .unwrap_or(VALIDATORS)
}

/// The only node whose absence drops the chain below the threshold.
///
/// With 22 / 21 / 21 that is node 1: losing it leaves 42, and losing either
/// other leaves 43, which still finalises with a tenth of a percent to spare.
pub(crate) fn stopper_index() -> usize {
    stake_split()
        .iter()
        .position(|held| !finalises(VALIDATORS - held))
        .unwrap_or(0)
}

fn banner(serving: Option<(&str, &str)>) {
    println!();
    println!("  Cupel network v{}", env!("CARGO_PKG_VERSION"));
    println!("  ---------------------------------------------------");
    if let Some((gateway_url, control_url)) = serving {
        println!("  RPC          {gateway_url}  (the gateway, across all three)");
        println!("  Control room {control_url}");
        println!();
    }
    for node in NODES {
        println!(
            "  {:<7} {:<11} rpc {}  beacon {}",
            node.name, node.consensus, node.rpc, node.beacon
        );
    }
    println!();
    println!("  Chain id     31337, {VALIDATORS} validators, {SECONDS_PER_SLOT}s slots, Electra");
    println!("  Finality     four epochs of 32 slots — about 25 minutes from genesis");
    println!("  Contracts    the same addresses as lab mode");
    println!();
    println!("  The first finalised epoch is about 25 minutes away.");
    println!("  cupel network status shows what all three think of the chain.");
    if serving.is_none() {
        println!();
        println!("  Detached: the gateway and the control room both live in the");
        println!("  cupel process, so neither is running. The clients' own ports");
        println!("  above still answer. `cupel network up` brings both up.");
    }
    if let Some((gateway_url, _)) = serving {
        println!();
        let held = stake_split();
        let total: usize = held.iter().sum();
        let stopper = stopper_index();
        println!(
            "  Stop node{}. The gateway routes around it and the chain keeps",
            stopper + 1
        );
        println!("  producing blocks — but it stops finalising: {total} validators");
        println!(
            "  split {} leave {} without it, and finality needs {}.",
            held.iter()
                .map(usize::to_string)
                .collect::<Vec<_>>()
                .join("/"),
            total - held[stopper],
            votes_needed()
        );
        println!("    docker stop {DEMO_STOP_CONTAINER}");
        println!("    curl -s {gateway_url}/health");
        println!("    cupel network status");
        println!();
        println!(
            "  Stop either other node instead and {} remain, which is still above",
            total - held[(stopper + 1) % held.len()]
        );
        println!("  the line — the chain barely notices. The threshold counts");
        println!("  validators, not nodes, and sixty-four does not divide by three.");
        println!();
        println!("  Ctrl-C stops the gateway. The devnet keeps running.");
    }
    println!();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_slot_duration_is_read_from_whichever_key_the_generator_wrote() {
        // The line ethereum-genesis-generator 6.2.1 actually writes, and the
        // one the previous parser could not see — which is why the check that
        // exists to catch a wrong slot time never once ran against a number.
        assert_eq!(
            declared_slot_millis("SLOT_DURATION_MS: 12000\n"),
            Some(SECONDS_PER_SLOT * 1000)
        );
        // The older spelling, still understood.
        assert_eq!(declared_slot_millis("SECONDS_PER_SLOT: 12\n"), Some(12_000));
        assert_eq!(
            declared_slot_millis("SECONDS_PER_SLOT: 6  # mainnet"),
            Some(6_000)
        );
        // A key that merely starts the same is a different key.
        assert_eq!(declared_slot_millis("SECONDS_PER_SLOT_EXTRA: 6\n"), None);
        // Neither key: the clients fall back to their preset, which is the
        // state this chain was in for its first two releases.
        let generated = "PRESET_BASE: 'mainnet'\nCONFIG_NAME: 'testnet'\nGENESIS_DELAY: 30\n";
        assert_eq!(declared_slot_millis(generated), None);
        // And the case the guard exists for, which it can now see.
        assert_ne!(
            declared_slot_millis("SLOT_DURATION_MS: 6000\n"),
            Some(SECONDS_PER_SLOT * 1000)
        );
    }

    #[test]
    fn the_assumed_slot_time_is_the_one_clients_fall_back_to() {
        // The generator declares no slot time, so the chain runs the preset
        // default. Anything else here is an assumption the chain does not
        // share, and every duration Cupel prints would be wrong by the ratio.
        assert_eq!(
            SECONDS_PER_SLOT, MAINNET_SECONDS_PER_SLOT,
            "a config with no SECONDS_PER_SLOT gives mainnet-preset slots"
        );
    }

    /// Which node the stop-a-node demo has to name, derived rather than asserted.
    ///
    /// Every place that told a reader to stop a node — this banner, walkthrough
    /// 3, the README, the design note — used to say that stopping any one of
    /// the three stopped finality, and named `cupel-el2`. That is true of equal
    /// thirds. This split is not equal: 64 across three is 22 / 21 / 21, so
    /// losing node 1 leaves 42 and stops, and losing either other leaves 43 and
    /// does not. A reader following the old instruction stopped node 2, watched
    /// finality carry on, and had no way to tell whether the lab or their
    /// understanding was broken.
    ///
    /// The evidence was already in the repository: under Fulu, Teku's 21
    /// validators published nothing for 147 slots and the chain finalised on
    /// the other two nodes' 67.19% — which is this same 43 of 64.
    #[test]
    fn only_one_node_holds_enough_stake_to_stop_finality() {
        let held = stake_split();
        assert_eq!(held, vec![22, 21, 21]);
        assert_eq!(held.iter().sum::<usize>(), VALIDATORS);

        // The boundary itself: two thirds of 64 is 42.67, so 42 is below.
        assert_eq!(votes_needed(), 43);
        assert!(!finalises(42));
        assert!(finalises(43));

        let survives: Vec<bool> = held.iter().map(|h| finalises(VALIDATORS - h)).collect();
        assert_eq!(
            survives,
            vec![false, true, true],
            "only the node holding the remainder can stop finality by leaving"
        );

        assert_eq!(stopper_index(), 0);
        assert_eq!(
            DEMO_STOP_CONTAINER,
            format!("cupel-el{}", stopper_index() + 1),
            "the demo must name the node whose absence actually stops finality"
        );
    }

    #[test]
    fn validators_are_split_with_the_remainder_first() {
        assert_eq!(validator_ranges(64, 3), vec![(0, 22), (22, 43), (43, 64)]);
        // Every validator is assigned exactly once, whatever the shape.
        for total in [1, 5, 64, 100] {
            for nodes in 1..=4 {
                let ranges = validator_ranges(total, nodes);
                assert_eq!(ranges.len(), nodes);
                assert_eq!(ranges[0].0, 0);
                assert_eq!(ranges[nodes - 1].1, total, "{total} across {nodes}");
                for pair in ranges.windows(2) {
                    assert_eq!(pair[0].1, pair[1].0, "a validator was skipped or shared");
                }
            }
        }
    }

    #[test]
    fn a_free_subnet_avoids_what_docker_already_has() {
        let taken = vec![
            "172.17.0.0/16".to_string(),
            "172.24.0.0/16".to_string(),
            "172.25.0.0/24".to_string(),
        ];
        assert_eq!(free_subnet(&taken), Some(26));
    }

    #[test]
    fn a_sixteen_swallows_the_twenty_four_inside_it() {
        // 172.24.0.0/16 contains 172.24.0.0/24, so matching on the second octet
        // rather than the literal string is the whole point.
        assert_eq!(free_subnet(&["172.24.0.0/16".to_string()]), Some(25));
    }

    #[test]
    fn wsls_own_subnet_is_never_offered() {
        // 172.29 is where WSL puts its interface. Handing it to Docker cuts the
        // host off from its own network.
        let taken: Vec<String> = (17..=32)
            .filter(|n| *n != 29)
            .map(|n| format!("172.{n}.0.0/16"))
            .collect();
        assert_eq!(free_subnet(&taken), None);
    }

    #[test]
    fn subnets_that_are_not_172_are_ignored() {
        assert_eq!(free_subnet(&["10.0.0.0/8".to_string()]), Some(24));
        assert_eq!(free_subnet(&["fd00::/64".to_string()]), Some(24));
    }

    #[test]
    fn node_ones_identity_is_fetched_once_and_then_kept() {
        let mut env = BTreeMap::new();
        assert!(needs_identity(&env), "nothing known yet");

        env.insert("CL_BOOTNODE".into(), String::new());
        env.insert("CL_STATIC_PEER".into(), String::new());
        assert!(needs_identity(&env), "written but empty is still not known");

        env.insert("CL_BOOTNODE".into(), "enr:-Oy4Q...".into());
        assert!(needs_identity(&env), "half of it is not enough");

        env.insert(
            "CL_STATIC_PEER".into(),
            "/ip4/172.24.0.21/tcp/9000/p2p/16U".into(),
        );
        assert!(!needs_identity(&env), "both known — leave the file alone");
    }

    #[test]
    fn the_fork_choice_and_the_client_flags_agree() {
        // Two halves of one decision, in two files. Turning Fulu back on
        // without making every node a supernode leaves a three-node network
        // unable to cover data column custody; making them supernodes without
        // Fulu is two hundred gossip topics for no reason, which is what broke
        // the subscription exchange between clients in the first place.
        let compose = include_str!("../../../compose/network.yml");
        let flags = [
            "--supernode",
            "--p2p-subscribe-all-custody-subnets-enabled=true",
        ];
        for flag in flags {
            // A comment may mention it; a command line may not.
            let used = compose
                .lines()
                .filter(|line| line.trim_start().starts_with("- "))
                .any(|line| line.contains(flag));
            assert!(
                !used,
                "{flag} is set, but this chain disables Fulu — turn both on or neither"
            );
        }
        assert_eq!(NEVER, "18446744073709551615", "Fulu must be disabled");
    }

    #[test]
    fn peers_are_pointed_at_quic_on_the_port_compose_opens() {
        let address = static_peer("172.24.0.21", "16Uiu2HAmAb");
        assert_eq!(address, "/ip4/172.24.0.21/udp/9001/quic-v1/p2p/16Uiu2HAmAb");

        // The port has to be the one Lighthouse was told to listen on, and the
        // two live in different files.
        let compose = include_str!("../../../compose/network.yml");
        assert!(
            compose.contains(&format!("--quic-port={CL_QUIC_PORT}")),
            "network.yml does not give node 1 --quic-port={CL_QUIC_PORT}"
        );
        // And it must be QUIC: over TCP, Teku never joined the gossip mesh.
        assert!(address.contains("/quic-v1/"), "{address}");
    }

    #[test]
    fn the_environment_file_survives_a_round_trip() {
        let mut env = BTreeMap::new();
        env.insert("CL_BOOTNODE".to_string(), String::new());
        env.insert("EL_BOOTNODE".to_string(), "enode://ab@1.2.3.4:30301".into());
        let rendered = render_env(&env);
        assert_eq!(parse_env(&rendered), env, "an empty value must survive");
        assert!(rendered.starts_with('#'), "the file explains itself");
    }

    #[test]
    fn the_premine_funds_every_development_account() {
        let premine: Value = serde_json::from_str(&premine()).expect("valid json");
        let accounts = premine.as_object().expect("an object");
        assert_eq!(accounts.len(), crate::DEV_ACCOUNTS.len());
        for (address, _) in crate::DEV_ACCOUNTS {
            assert_eq!(
                accounts[address]["balance"], "10000ETH",
                "{address} is funded differently in network mode than in lab mode"
            );
        }
    }

    #[test]
    fn compose_reads_the_password_file_that_init_writes() {
        // Two files in two languages that have to agree on one name. A mismatch
        // is silent: Prysm restarts every minute, its validators never attest,
        // and the only visible symptom is a chain that will not finalise.
        let compose = include_str!("../../../compose/network.yml");
        assert!(
            compose.contains(&format!("--wallet-password-file=/keys/{PRYSM_PASSWORD}")),
            "compose/network.yml does not read /keys/{PRYSM_PASSWORD}"
        );
    }

    #[test]
    fn every_execution_node_announces_the_address_it_is_on() {
        // --nat extip is what an execution node tells its peers to dial back on,
        // and the file's own header calls a wrong one the commonest reason a
        // local devnet forms no peers. The three nodes share one command block
        // and differ only in SELF_IP, so the check is that each service's
        // SELF_IP names the same variable as its ipv4_address.
        let compose = include_str!("../../../compose/network.yml");
        for service in compose.split("\n  el") {
            let Some(self_ip) = between(service, "SELF_IP: ${", "}") else {
                continue;
            };
            let address = between(service, "ipv4_address: ${", "}")
                .expect("a service that sets SELF_IP also has an address");
            assert_eq!(
                self_ip, address,
                "an execution node announces ${{{self_ip}}} but sits at ${{{address}}}"
            );
        }
    }

    #[test]
    fn every_execution_node_publishes_its_websocket() {
        // The control room subscribes to `newHeads` over a socket, and geth
        // refuses a browser origin it was not told about — which looks from
        // the page like a socket that closes the moment it opens. The flags
        // live in the shared command block; the port each node publishes is
        // its own, one above the JSON-RPC block.
        let compose = include_str!("../../../compose/network.yml");
        for flag in ["--ws --ws.addr 0.0.0.0 --ws.port 8546", "--ws.origins '*'"] {
            assert!(
                compose.contains(flag),
                "compose/network.yml does not pass {flag}"
            );
        }
        for (index, port) in [(1, 8558), (2, 8559), (3, 8560)] {
            let service = compose
                .split("\n  el")
                .find(|service| service.starts_with(&format!("{index}:")))
                .unwrap_or_else(|| panic!("compose/network.yml has no service el{index}"));
            let mapping = format!("\"127.0.0.1:{port}:8546\"");
            assert!(
                service.contains(&mapping),
                "el{index} does not publish its websocket on {port}"
            );
        }
    }

    /// The text between two markers, if both are present in order.
    fn between<'a>(haystack: &'a str, open: &str, close: &str) -> Option<&'a str> {
        let start = haystack.find(open)? + open.len();
        let rest = &haystack[start..];
        Some(&rest[..rest.find(close)?])
    }

    #[test]
    fn compose_references_no_address_init_does_not_write() {
        // compose interpolates a name it was never given as an empty string and
        // carries on, so a typo here becomes a container with no address rather
        // than an error naming the variable.
        let compose = include_str!("../../../compose/network.yml");
        let written: Vec<String> = [
            "CUPEL_SUBNET",
            "IP_BOOTNODE",
            "EL_BOOTNODE",
            "EL_BOOTNODE_KEY",
            "CL_BOOTNODE",
            "CL_STATIC_PEER",
            "IP_VC1",
            "IP_VC2",
        ]
        .iter()
        .map(|s| s.to_string())
        .chain((1..=NODES.len()).flat_map(|n| [format!("IP_EL{n}"), format!("IP_CL{n}")]))
        .collect();

        for (index, _) in compose.match_indices("${") {
            let rest = &compose[index + 2..];
            let name = &rest[..rest.find('}').expect("an interpolation is closed")];
            assert!(
                written.contains(&name.to_string()),
                "compose reads ${{{name}}}, which `network init` never writes"
            );
        }
    }

    #[test]
    fn every_node_has_its_own_ports() {
        let mut seen = Vec::new();
        for node in NODES {
            assert!(
                !seen.contains(&node.rpc),
                "{} reuses an rpc port",
                node.name
            );
            assert!(
                !seen.contains(&node.beacon),
                "{} reuses a beacon port",
                node.name
            );
            seen.push(node.rpc);
            seen.push(node.beacon);
        }
        // Lab mode holds 8545 for the gateway and 8546/8547 for its node.
        for node in NODES {
            assert!(
                !node.rpc.ends_with(":8545"),
                "{} collides with the gateway",
                node.name
            );
        }
    }
}
